version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./real-world:/real-world

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    # volumes:
    #   - ./docker/db/data:/var/lib/mysql
