version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./real-world:/real-world

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
