version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    environment:
      - RAILS_ENV=production
    volumes:
      - ./real-world:/real-world

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
